basePath: /
definitions:
  schemas.GetCaptchaResponse:
    properties:
      captcha_id:
        type: string
      captcha_url:
        type: string
    type: object
host: api.shunjiecloud.com
info:
  contact:
    email: zhou_shengjie@outlook.com
    name: zhoushengjie
    url: https://www.shunjiecloud.com
  description: 瞬捷云 captcha-api 验证码服务api
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://www.shunjiecloud.com
  title: 瞬捷云验证码服务api
  version: "1.0"
paths:
  /captcha/v1/captcha:
    get:
      consumes:
      - application/json
      description: 获取验证码地址。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.GetCaptchaResponse'
      summary: 获取验证码地址
      tags:
      - 验证码
  /captcha/v1/captcha/{filename}:
    get:
      consumes:
      - application/json
      description: 根据验证码地址，获取验证码图片。
      parameters:
      - description: 验证码图片名，例如：o5CaUbWHwjRUg6tyYrBW.png
        in: path
        name: filename
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: 验证码图片
        "400":
          description: 404 page not found
          schema:
            type: string
      summary: 验证码图片
      tags:
      - 验证码
swagger: "2.0"
